import AddMotion from './AddMotion';
import AddAltMotion from './AddAltMotion';
import AddFilledMotion from './AddFilledMotion';
import AppsMotion from './AppsMotion';
import ArrowUpMotion from './ArrowUpMotion';
import ArrowDownMotion from './ArrowDownMotion';
import ArrowDownLeftMotion from './ArrowDownLeftMotion';
import ArrowDownRightMotion from './ArrowDownRightMotion';
import ArrowLeftMotion from './ArrowLeftMotion';
import ArrowRightMotion from './ArrowRightMotion';
import ArrowUpLeftMotion from './ArrowUpLeftMotion';
import ArrowUpRightMotion from './ArrowUpRightMotion';
import ChevronDownMotion from './ChevronDownMotion';
import ChevronUpMotion from './ChevronUpMotion';
import ChevronLeftMotion from './ChevronLeftMotion';
import ChevronRightMotion from './ChevronRightMotion';
import CaretDownMotion from './CaretDownMotion';
import CaretUpMotion from './CaretUpMotion';
import CaretLeftMotion from './CaretLeftMotion';
import CaretRightMotion from './CaretRightMotion';
import CloseMotion from './CloseMotion';
import CloseFilledMotion from './CloseFilledMotion';
import CloseOutlineMotion from './CloseOutlineMotion';
import DownToBottomMotion from './DownToBottomMotion';
import DraggableMotion from './DraggableMotion';
import HomeMotion from './HomeMotion';
import MenuMotion from './MenuMotion';
import OverflowMenuHorizontalMotion from './OverflowMenuHorizontalMotion';
import OverflowMenuVerticalMotion from './OverflowMenuVerticalMotion';
import PageFirstMotion from './PageFirstMotion';
import PageLastMotion from './PageLastMotion';
import SubtractMotion from './SubtractMotion';
import SubtractAltMotion from './SubtractAltMotion';import SwitcherMotion from './SwitcherMotion';
import SelectWindowMotion from './SelectWindowMotion';
import UpToTopMotion from './UpToTopMotion';
import ZoomInAreaMotion from './ZoomInAreaMotion';
import ZoomAreaMotion from './ZoomAreaMotion';
import ZoomOutAreaMotion from './ZoomOutAreaMotion';
import ZoomFitMotion from './ZoomFitMotion';
import ZoomInMotion from './ZoomInMotion';
import ZoomOutMotion from './ZoomOutMotion';
import ZoomResetMotion from './ZoomResetMotion';

import AddToSubtractMotion from './AddToSubtractMotion';
import MenuToCloseMotion from './MenuToCloseMotion';
import SwitcherToCloseMotion from './SwitcherToCloseMotion';



export { AddMotion, AddAltMotion, AddFilledMotion, AppsMotion, ArrowUpMotion, ArrowDownMotion, ArrowDownLeftMotion, ArrowDownRightMotion, ArrowLeftMotion, ArrowRightMotion, ArrowUpLeftMotion, ArrowUpRightMotion, ChevronDownMotion, ChevronUpMotion, ChevronLeftMotion, ChevronRightMotion, CaretDownMotion, CaretUpMotion, CaretLeftMotion, CaretRightMotion, CloseMotion, CloseOutlineMotion, CloseFilledMotion, DownToBottomMotion, DraggableMotion, HomeMotion, MenuMotion, OverflowMenuHorizontalMotion, OverflowMenuVerticalMotion, PageFirstMotion, PageLastMotion,SubtractMotion, SubtractAltMotion, SelectWindowMotion, SwitcherMotion,  UpToTopMotion, ZoomInAreaMotion, ZoomAreaMotion, ZoomOutAreaMotion, ZoomFitMotion, ZoomInMotion, ZoomOutMotion, ZoomResetMotion, AddToSubtractMotion, MenuToCloseMotion, SwitcherToCloseMotion };
